# Generated by Django 3.2.14 on 2023-01-06 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('EventID', models.AutoField(primary_key=True, serialize=False)),
                ('Event_Name', models.CharField(max_length=255)),
                ('Event_Catogary', models.CharField(choices=[('Food', 'Food'), ('Photography', 'Photography'), ('Decorations', 'Decorations'), ('Beauty', 'Beauty'), ('FullEvent', 'FullEvent')], max_length=255)),
                ('Event_Price', models.CharField(max_length=255)),
                ('Event_Discription', models.CharField(max_length=1000)),
                ('Image', models.ImageField(upload_to='Eventimage')),
                ('EventProvider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
