# Generated by Django 3.2.14 on 2023-01-07 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Events', '0002_alter_eventmodel_eventprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBookings',
            fields=[
                ('BookingID', models.AutoField(primary_key=True, serialize=False)),
                ('BookedDate', models.DateField(auto_now_add=True)),
                ('EventDate', models.DateField()),
                ('Name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=1000)),
                ('Phonenumber', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('GuestNumber', models.CharField(max_length=255)),
                ('BookedBY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('EventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.eventmodel')),
            ],
        ),
    ]
