# Generated by Django 3.2.14 on 2023-01-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_eventbookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbookings',
            name='Approval_Status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='Advance_Payment',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='InstaID',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
