# Generated by Django 4.2.7 on 2025-01-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_auto_20230121_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbookings',
            name='GuestNumber',
            field=models.PositiveIntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eventbookings',
            name='Phonenumber',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='Advance_Payment',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='Event_Price',
            field=models.PositiveIntegerField(),
        ),
    ]
