# Generated by Django 4.2.7 on 2025-01-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_alter_eventbookings_guestnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbookings',
            name='BookedDate',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventbookings',
            name='GuestNumber',
            field=models.PositiveIntegerField(),
        ),
    ]
