# Generated by Django 4.2.7 on 2025-02-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0007_eventbookings_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbookings',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='eventbookings',
            name='EventTime',
            field=models.DateTimeField(null=True),
        ),
    ]
