# Generated by Django 4.2.7 on 2025-02-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0008_remove_eventbookings_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbookings',
            name='EventTime',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='EventTime',
            field=models.DateTimeField(null=True),
        ),
    ]
