# Generated by Django 4.2.7 on 2025-02-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0009_remove_eventbookings_eventtime_eventmodel_eventtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='EventTime',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
