# Generated by Django 4.2.7 on 2025-02-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0010_alter_eventmodel_eventtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='EventTime',
            new_name='Time',
        ),
        migrations.AddField(
            model_name='eventbookings',
            name='EventTime',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
